[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
reign_task = { path = "../../../reign_task" }
reign_common_tasks = { path = "../../../utils/reign_common_tasks" }
