base_url = "https://reign.rs"

title = "Reign"
description = "Opinionated Fullstack Web Framework in Rust"

build_search_index = true
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "material-light"

external_links_target_blank = true

languages = [
	{ code = "ru", search = true },
]

[translations]
news = "News"
search = "Search"
release = "Release"
language = "Language"
guide = "Guide"
reference = "Reference"
code = "Code"

[languages.ru.translations]
news = "Новости"
search = "Поиск"
release = "Релиз"
language = "Язык"
guide = "Руководство"
reference = "Ссылка"
code = "Код"

[extra]
releases = [
]
languages = { en = "English", ru = "Pусский" }
