[package]
name = "reign_examples_views_gotham"
version = "0.1.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reign = { path = "../../../../reign", features = ["views-gotham"], default-features = false }
gotham = "0.5"
