pub const DOCTYPE: &str = "(?i)<!DOCTYPE [^>]+>";
pub const TAG_NAME: &str = "[[:alpha:]](:?[a-zA-Z0-9\\-]*[[:alnum:]])?";
pub const ATTR_NAME: &str = "[^\\s\"\'>/=]+";
pub const VAR_ATTR_SYMBOL: &str = ":";
pub const CTRL_ATTR: &str = "!(for|if|else-if|else)";
pub const DY_ATTR_NAME_PART: &str = "[^\\{}\\s\"\'>/=]*";
pub const DY_ATTR_EXPR: &str = "\\{\\{([^=]+)}}";
pub const ATTR_VALUE_DOUBLE_QUOTED: &str = "\"([^\"]*)\"";
pub const ATTR_VALUE_SINGLE_QUOTED: &str = "'([^']*)'";
pub const ATTR_VALUE_UNQUOTED: &str = "[^\\s\"'=<>`]+";

pub const HTML_TAGS: [&str; 116] = [
    "html",
    "body",
    "base",
    "head",
    "link",
    "meta",
    "style",
    "title",
    "address",
    "article",
    "aside",
    "footer",
    "header",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hgroup",
    "nav",
    "section",
    "div",
    "dd",
    "dl",
    "dt",
    "figcaption",
    "figure",
    "picture",
    "hr",
    "img",
    "li",
    "main",
    "ol",
    "p",
    "pre",
    "ul",
    "a",
    "b",
    "abbr",
    "bdi",
    "bdo",
    "br",
    "cite",
    "code",
    "data",
    "dfn",
    "em",
    "i",
    "kbd",
    "mark",
    "q",
    "rp",
    "rt",
    "rtc",
    "ruby",
    "s",
    "samp",
    "small",
    "span",
    "strong",
    "sub",
    "sup",
    "time",
    "u",
    "var",
    "wbr",
    "area",
    "audio",
    "map",
    "track",
    "video",
    "embed",
    "object",
    "param",
    "source",
    "canvas",
    "script",
    "noscript",
    "del",
    "ins",
    "caption",
    "col",
    "colgroup",
    "table",
    "thead",
    "tbody",
    "td",
    "th",
    "tr",
    "button",
    "datalist",
    "fieldset",
    "form",
    "input",
    "label",
    "legend",
    "meter",
    "optgroup",
    "option",
    "output",
    "progress",
    "select",
    "textarea",
    "details",
    "dialog",
    "menu",
    "menuitem",
    "summary",
    "content",
    "element",
    "shadow",
    "template",
    "blockquote",
    "iframe",
    "tfoot",
];

pub const VOID_TAGS: [&str; 14] = [
    "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source",
    "track", "wbr",
];

pub const SVG_TAGS: [&str; 30] = [
    "svg",
    "animate",
    "circle",
    "clippath",
    "cursor",
    "defs",
    "desc",
    "ellipse",
    "filter",
    "font-face",
    "foreignobject",
    "g",
    "glyph",
    "image",
    "line",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "rect",
    "switch",
    "symbol",
    "text",
    "textpath",
    "tspan",
    "use",
    "view",
];
